### PR TITLE
Add 616D and 1037D solutions

### PR DESCRIPTION
**Pull request by daniddelrio**

### CODE REVIEW

**Comment by virejdasani** [comment]
Hi, thanks for contributing! Just one minor thing: Make sure the link to the problem set is on the FIRST line not the second line

**Comment by daniddelrio** [comment]
Done, much appreciated as well!

**Comment by virejdasani** [comment]
Looks good, going ahead with the merge :)

**Comment by virejdasani** [comment]
@all-contributors please add @daniddelrio for code

**Pull request merged**
